import { useEffect, useState } from "react";
import { FaTimes, FaExchangeAlt } from "react-icons/fa";
import "../../../css/orders.css";

const initialForm = { strategy: "", comment: "", account_id: "", symbol_id: "", order_type: "MARKET", side: "BUY", volume: 1, requested_price: "", stop_loss: "", take_profit: "" };
const OrderForm = ({ isOpen, onClose, onSubmit, order, accounts, symbols, loading }) => {
  const [formData, setFormData] = useState(initialForm);
  const [error, setError] = useState("");
  useEffect(() => { if (isOpen) { setFormData(order ? { ...initialForm, ...order } : { ...initialForm, account_id: accounts[0]?.id || "", symbol_id: symbols[0]?.id || "" }); setError(""); } }, [isOpen, order, accounts, symbols]);
  if (!isOpen) return null;
  const handleChange = (event) => { const { name, value } = event.target; setFormData((previous) => ({ ...previous, [name]: value })); };
  const handleSubmit = (event) => { event.preventDefault(); if (!formData.strategy.trim() || !formData.account_id || !formData.symbol_id || Number(formData.volume) <= 0) { setError("Strategy, account, symbol, and a positive volume are required."); return; } if (["LIMIT", "STOP"].includes(formData.order_type) && Number(formData.requested_price) <= 0) { setError("Requested price is required for limit and stop orders."); return; } const numeric = ["volume", "requested_price", "stop_loss", "take_profit"]; const payload = Object.fromEntries(Object.entries(formData).map(([key, value]) => [key, numeric.includes(key) ? (value === "" ? null : Number(value)) : value])); onSubmit(payload); };
  return <div className="order-modal-overlay" onMouseDown={(event) => event.target === event.currentTarget && !loading && onClose()}><div className="order-modal"><header className="order-modal__header"><div><span className="orders-eyebrow">ORDER WORKFLOW</span><h2>{order ? "Edit Order" : "Create Order"}</h2><p>Submit an instruction to the AQE execution pipeline.</p></div><button type="button" onClick={onClose} disabled={loading} aria-label="Close"><FaTimes /></button></header>{error && <div className="order-form-error">{error}</div>}<form className="order-form" onSubmit={handleSubmit}><div className="order-form__grid"><label>Strategy<input name="strategy" value={formData.strategy} onChange={handleChange} placeholder="Strategy name" /></label><label>Order Type<select name="order_type" value={formData.order_type} onChange={handleChange} disabled={!!order}><option>MARKET</option><option>LIMIT</option><option>STOP</option></select></label><label>Account<select name="account_id" value={formData.account_id} onChange={handleChange} disabled={!!order}><option value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.account_name || account.account_number}</option>)}</select></label><label>Symbol<select name="symbol_id" value={formData.symbol_id} onChange={handleChange} disabled={!!order}><option value="">Select symbol</option>{symbols.map((symbol) => <option key={symbol.id} value={symbol.id}>{symbol.name}</option>)}</select></label><label>Side<select name="side" value={formData.side} onChange={handleChange}><option>BUY</option><option>SELL</option></select></label><label>Volume<input type="number" name="volume" min="0.0001" step="any" value={formData.volume} onChange={handleChange} /></label><label>Requested Price<input type="number" name="requested_price" min="0" step="any" value={formData.requested_price} onChange={handleChange} placeholder={formData.order_type === "MARKET" ? "Optional for market" : "Required"} /></label><label>Stop Loss<input type="number" name="stop_loss" min="0" step="any" value={formData.stop_loss} onChange={handleChange} /></label><label>Take Profit<input type="number" name="take_profit" min="0" step="any" value={formData.take_profit} onChange={handleChange} /></label><label className="order-form__wide">Comment<textarea name="comment" rows="2" value={formData.comment || ""} onChange={handleChange} placeholder="Optional execution note" /></label></div><footer className="order-form__footer"><button type="button" className="order-button order-button--muted" onClick={onClose} disabled={loading}>Cancel</button><button type="submit" className="order-button order-button--primary" disabled={loading}><FaExchangeAlt />{loading ? "Saving..." : order ? "Save Changes" : "Create Order"}</button></footer></form></div></div>;
};
export default OrderForm;
