"""
Core enumerations for the AQE strategy engine.

This module contains domain-level enums shared by:
- strategies
- market-data layer
- signal generation
- backtesting
- risk engine
- execution engine

Keep this module dependency-light. It must not import MT5, SQLAlchemy,
FastAPI, pandas, or other infrastructure-specific packages.
"""

from enum import Enum


class Direction(str, Enum):
    """Trading direction."""

    BUY = "BUY"
    SELL = "SELL"


class SignalType(str, Enum):
    """Type of signal generated by a strategy."""

    ENTRY = "ENTRY"
    EXIT = "EXIT"
    REVERSAL = "REVERSAL"


class SignalStatus(str, Enum):
    """Lifecycle status of a strategy signal."""

    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    EXECUTED = "EXECUTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class Timeframe(str, Enum):
    """
    Supported market-data timeframes.

    Values intentionally follow MT5 timeframe naming so that the
    MT5 bridge can map them cleanly later.
    """

    M1 = "M1"
    M2 = "M2"
    M3 = "M3"
    M4 = "M4"
    M5 = "M5"
    M6 = "M6"
    M10 = "M10"
    M12 = "M12"
    M15 = "M15"
    M20 = "M20"
    M30 = "M30"

    H1 = "H1"
    H2 = "H2"
    H3 = "H3"
    H4 = "H4"
    H6 = "H6"
    H8 = "H8"
    H12 = "H12"

    D1 = "D1"
    W1 = "W1"
    MN1 = "MN1"


class StrategyCategory(str, Enum):
    """High-level classification of a trading strategy."""

    TREND = "TREND"
    BREAKOUT = "BREAKOUT"
    MEAN_REVERSION = "MEAN_REVERSION"
    LIQUIDITY = "LIQUIDITY"
    SMC = "SMC"
    SCALPING = "SCALPING"
    EXPERIMENTAL = "EXPERIMENTAL"


class MarketRegime(str, Enum):
    """
    Broad market regimes used by strategies and, later, the
    strategy-selection/AI layers.
    """

    TRENDING = "TRENDING"
    RANGING = "RANGING"
    VOLATILE = "VOLATILE"
    LOW_VOLATILITY = "LOW_VOLATILITY"
    TRANSITIONING = "TRANSITIONING"
    UNKNOWN = "UNKNOWN"


class OrderType(str, Enum):
    """
    Order intent produced after a strategy signal has passed
    through the appropriate processing layers.
    """

    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"


class PriceSource(str, Enum):
    """Source of price/market data."""

    MT5 = "MT5"
    BACKTEST = "BACKTEST"
    SIMULATION = "SIMULATION"
    HISTORICAL = "HISTORICAL"


class StrategyExecutionMode(str, Enum):
    """Environment in which a strategy is running."""

    BACKTEST = "BACKTEST"
    PAPER = "PAPER"
    LIVE = "LIVE"