"""
Trading signal models for the AQE strategy engine.

A Signal represents a strategy's trading decision.

Important:
    A Signal is NOT an order.

The strategy layer generates signals.
The risk engine validates them.
The execution layer converts approved signals into orders.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from .enums import (
    Direction,
    OrderType,
    SignalStatus,
    SignalType,
    Timeframe,
)


class Signal(BaseModel):
    """
    Represents a trading signal generated by a strategy.

    A signal contains the strategy's trading intent and the prices
    required for downstream risk and execution processing.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
    )

    # ------------------------------------------------------------------
    # Identity
    # ------------------------------------------------------------------

    signal_id: str = Field(min_length=1)

    strategy_id: str = Field(min_length=1)

    symbol: str = Field(min_length=1)

    timeframe: Timeframe

    # ------------------------------------------------------------------
    # Signal classification
    # ------------------------------------------------------------------

    signal_type: SignalType

    direction: Direction

    order_type: OrderType = OrderType.MARKET

    status: SignalStatus = SignalStatus.ACTIVE

    # ------------------------------------------------------------------
    # Pricing
    # ------------------------------------------------------------------

    entry_price: Decimal = Field(gt=0)

    stop_loss: Decimal | None = Field(
        default=None,
        gt=0,
    )

    take_profit: Decimal | None = Field(
        default=None,
        gt=0,
    )

    # ------------------------------------------------------------------
    # Strategy assessment
    # ------------------------------------------------------------------

    confidence: Decimal = Field(
        ge=Decimal("0"),
        le=Decimal("1"),
    )

    # ------------------------------------------------------------------
    # Timing
    # ------------------------------------------------------------------

    created_at: datetime

    expires_at: datetime | None = None

    # ------------------------------------------------------------------
    # Additional strategy information
    # ------------------------------------------------------------------

    reason: str | None = None

    metadata: dict[str, object] = Field(
        default_factory=dict,
    )

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    @model_validator(mode="after")
    def validate_signal(self) -> "Signal":
        """Validate the relationship between signal fields."""

        if self.stop_loss is not None:
            if self.direction == Direction.BUY:
                if self.stop_loss >= self.entry_price:
                    raise ValueError("BUY stop_loss must be below entry_price")

            elif self.direction == Direction.SELL:
                if self.stop_loss <= self.entry_price:
                    raise ValueError("SELL stop_loss must be above entry_price")

        if self.take_profit is not None:
            if self.direction == Direction.BUY:
                if self.take_profit <= self.entry_price:
                    raise ValueError("BUY take_profit must be above entry_price")

            elif self.direction == Direction.SELL:
                if self.take_profit >= self.entry_price:
                    raise ValueError("SELL take_profit must be below entry_price")

        if self.expires_at is not None:
            if self.expires_at <= self.created_at:
                raise ValueError("expires_at must be later than created_at")

        return self

    # ------------------------------------------------------------------
    # Convenience properties
    # ------------------------------------------------------------------

    @property
    def has_stop_loss(self) -> bool:
        """Return whether the signal contains a stop loss."""

        return self.stop_loss is not None

    @property
    def has_take_profit(self) -> bool:
        """Return whether the signal contains a take profit."""

        return self.take_profit is not None

    @property
    def risk_distance(self) -> Decimal | None:
        """
        Return the absolute entry-to-stop distance.

        This is useful to the risk engine when calculating position size.
        """

        if self.stop_loss is None:
            return None

        return abs(self.entry_price - self.stop_loss)

    @property
    def reward_distance(self) -> Decimal | None:
        """
        Return the absolute entry-to-target distance.
        """

        if self.take_profit is None:
            return None

        return abs(self.take_profit - self.entry_price)

    @property
    def risk_reward_ratio(self) -> Decimal | None:
        """
        Return the theoretical reward-to-risk ratio.

        Returns None when either stop loss or take profit is missing.
        """

        if self.risk_distance is None:
            return None

        if self.reward_distance is None:
            return None

        if self.risk_distance == 0:
            return None

        return self.reward_distance / self.risk_distance

    @property
    def is_entry(self) -> bool:
        """Return whether this is an entry signal."""

        return self.signal_type == SignalType.ENTRY

    @property
    def is_exit(self) -> bool:
        """Return whether this is an exit signal."""

        return self.signal_type == SignalType.EXIT

    @property
    def is_active(self) -> bool:
        """Return whether the signal is currently active."""

        return self.status == SignalStatus.ACTIVE
