from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class PositionResponse(BaseModel):
    """
    Normalized representation of an open MetaTrader 5 position.

    Important:
    - ticket is the MT5 position ticket.
    - identifier is the MT5 position identifier.
    - Neither field represents an originating order or deal ID.
    """

    model_config = ConfigDict(extra="ignore")

    # ------------------------------------------------------------------
    # Position identity
    # ------------------------------------------------------------------

    ticket: int = Field(gt=0)
    identifier: int = Field(gt=0)

    # ------------------------------------------------------------------
    # Broker / strategy metadata
    # ------------------------------------------------------------------

    symbol: str = Field(min_length=1)
    magic: int = Field(default=0, ge=0)
    reason: int = Field(default=0, ge=0)
    comment: str = ""

    # ------------------------------------------------------------------
    # Position state
    # ------------------------------------------------------------------

    type: int = Field(ge=0)
    volume: float = Field(gt=0)

    price_open: float = Field(gt=0)
    price_current: float = Field(gt=0)

    sl: float = Field(default=0.0, ge=0)
    tp: float = Field(default=0.0, ge=0)

    # ------------------------------------------------------------------
    # Financial state
    # ------------------------------------------------------------------

    swap: float = 0.0
    profit: float = 0.0

    # ------------------------------------------------------------------
    # MT5 timestamps
    # ------------------------------------------------------------------

    time: int = Field(ge=0)
    time_msc: int = Field(ge=0)

    time_update: int = Field(ge=0)
    time_update_msc: int = Field(ge=0)


class PositionCloseResponse(BaseModel):
    """
    Result of closing an MT5 position.

    Unlike PositionResponse, this response can contain the
    order/deal identifiers generated by the close transaction.
    """

    model_config = ConfigDict(extra="ignore")

    ticket: int = Field(gt=0)
    symbol: str = Field(min_length=1)
    volume: float = Field(gt=0)

    retcode: int
    comment: str = ""

    order: int | None = None
    deal: int | None = None
    position: int | None = None


class PositionModifyRequest(BaseModel):
    """Request to modify an MT5 position's SL/TP."""

    model_config = ConfigDict(extra="forbid")

    sl: float | None = Field(default=None, gt=0)
    tp: float | None = Field(default=None, gt=0)


class PositionModifyResponse(BaseModel):
    """Result of modifying an MT5 position."""

    model_config = ConfigDict(extra="ignore")

    ticket: int = Field(gt=0)
    symbol: str = Field(min_length=1)

    sl: float = Field(ge=0)
    tp: float = Field(ge=0)

    retcode: int
    comment: str = ""
