"""update order broker identifiers

Revision ID: 2587a2e5e4b8
Revises: b2cd034feb30
Create Date: 2026-09-24 07:43:26.953626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2587a2e5e4b8'
down_revision: Union[str, Sequence[str], None] = 'b2cd034feb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('broker_order_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('broker_deal_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('broker_position_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_orders_ticket'), table_name='orders')
    op.drop_constraint(op.f('orders_ticket_key'), 'orders', type_='unique')
    op.create_index('ix_orders_broker_deal_id', 'orders', ['broker_deal_id'], unique=False)
    op.create_index('ix_orders_broker_order_id', 'orders', ['broker_order_id'], unique=False)
    op.create_index('ix_orders_broker_position_id', 'orders', ['broker_position_id'], unique=False)
    op.create_unique_constraint(None, 'orders', ['broker_deal_id'])
    op.create_unique_constraint(None, 'orders', ['broker_position_id'])
    op.create_unique_constraint(None, 'orders', ['broker_order_id'])
    op.drop_column('orders', 'ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ticket', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_index('ix_orders_broker_position_id', table_name='orders')
    op.drop_index('ix_orders_broker_order_id', table_name='orders')
    op.drop_index('ix_orders_broker_deal_id', table_name='orders')
    op.create_unique_constraint(op.f('orders_ticket_key'), 'orders', ['ticket'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orders_ticket'), 'orders', ['ticket'], unique=False)
    op.drop_column('orders', 'broker_position_id')
    op.drop_column('orders', 'broker_deal_id')
    op.drop_column('orders', 'broker_order_id')
    # ### end Alembic commands ###
