"""initial schema

Revision ID: 304f2632f8cf
Revises: 
Create Date: 2026-09-16 11:44:43.409662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304f2632f8cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_candles',
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('spread', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_market_candle')
    )
    op.create_index('ix_market_candles_lookup', 'market_candles', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('symbols',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('asset_class', sa.Enum('FOREX', 'CRYPTO', 'METALS', 'INDICES', 'STOCKS', 'COMMODITIES', name='asset_class_enum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_symbols_active', 'symbols', ['active'], unique=False)
    op.create_index('ix_symbols_asset_class', 'symbols', ['asset_class'], unique=False)
    op.create_index('ix_symbols_name', 'symbols', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_email_verification_expires', 'email_verifications', ['expires_at'], unique=False)
    op.create_index('ix_email_verification_user', 'email_verifications', ['user_id'], unique=False)
    op.create_index('ix_email_verification_verified', 'email_verifications', ['verified'], unique=False)
    op.create_table('historical_candles',
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('spread', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'timestamp', name='uq_historical_candle_symbol_timeframe_timestamp')
    )
    op.create_index('ix_historical_candles_symbol_timeframe_timestamp', 'historical_candles', ['symbol_id', 'timeframe', 'timestamp'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('strategy_runs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.String(length=30), nullable=False),
    sa.Column('run_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('run_type', sa.Enum('BACKTEST', 'PAPER', 'LIVE', name='strategy_run_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='strategy_run_status_enum'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_strategy_name', 'strategy_runs', ['strategy_name'], unique=False)
    op.create_index('ix_strategy_started', 'strategy_runs', ['started_at'], unique=False)
    op.create_index('ix_strategy_status', 'strategy_runs', ['status'], unique=False)
    op.create_index('ix_strategy_type', 'strategy_runs', ['run_type'], unique=False)
    op.create_table('trading_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.Enum('MT5', 'BINANCE', 'FIX', name='broker_type_enum'), nullable=False),
    sa.Column('login', sa.Integer(), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('bridge_url', sa.String(length=255), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'ARCHIVED', name='account_status_enum'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'server', 'login', name='uq_trading_account_identity')
    )
    op.create_index('ix_trading_accounts_broker', 'trading_accounts', ['broker'], unique=False)
    op.create_index('ix_trading_accounts_status', 'trading_accounts', ['status'], unique=False)
    op.create_index('ix_trading_accounts_user_id', 'trading_accounts', ['user_id'], unique=False)
    op.create_table('account_symbols',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('broker_symbol', sa.String(length=50), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('currency_base', sa.String(length=10), nullable=True),
    sa.Column('currency_profit', sa.String(length=10), nullable=True),
    sa.Column('currency_margin', sa.String(length=10), nullable=True),
    sa.Column('digits', sa.Integer(), nullable=False),
    sa.Column('point', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('contract_size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('min_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_volume', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_step', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'broker_symbol', name='uq_account_broker_symbol'),
    sa.UniqueConstraint('account_id', 'symbol_id', name='uq_account_symbol')
    )
    op.create_index('ix_account_symbols_account_id', 'account_symbols', ['account_id'], unique=False)
    op.create_index('ix_account_symbols_broker_symbol', 'account_symbols', ['broker_symbol'], unique=False)
    op.create_index('ix_account_symbols_enabled', 'account_symbols', ['enabled'], unique=False)
    op.create_index('ix_account_symbols_symbol_id', 'account_symbols', ['symbol_id'], unique=False)
    op.create_table('orders',
    sa.Column('ticket', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', name='order_type_enum'), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side_enum'), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('executed_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'PENDING', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='order_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_index('ix_orders_account_id', 'orders', ['account_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_strategy', 'orders', ['strategy'], unique=False)
    op.create_index('ix_orders_symbol_id', 'orders', ['symbol_id'], unique=False)
    op.create_index('ix_orders_ticket', 'orders', ['ticket'], unique=False)
    op.create_table('performance',
    sa.Column('strategy_run_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'BACKTEST', 'LIVE', name='performance_period_enum'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('breakeven_trades', sa.Integer(), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_swap', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calmar_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_drawdown_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('average_r_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('recovery_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('payoff_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('average_trade_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('average_win', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('average_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('largest_win', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('largest_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ending_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('lowest_equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_run_id')
    )
    op.create_index('ix_performance_created', 'performance', ['created_at'], unique=False)
    op.create_index('ix_performance_period', 'performance', ['period'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_open_positions', sa.Integer(), nullable=False),
    sa.Column('total_open_orders', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exposure', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exposure_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('floating_profit_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('daily_drawdown', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('daily_drawdown_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_drawdown_percent', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('value_at_risk', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_shortfall', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('portfolio_heat', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('risk_per_trade', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_open_risk', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('correlation_risk', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'), nullable=False),
    sa.Column('daily_loss_limit_hit', sa.Boolean(), nullable=False),
    sa.Column('weekly_loss_limit_hit', sa.Boolean(), nullable=False),
    sa.Column('trading_halted', sa.Boolean(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_account', 'risk_snapshots', ['account_id'], unique=False)
    op.create_index('ix_risk_level', 'risk_snapshots', ['risk_level'], unique=False)
    op.create_index('ix_risk_timestamp', 'risk_snapshots', ['snapshot_time'], unique=False)
    op.create_table('positions',
    sa.Column('ticket', sa.Integer(), nullable=False),
    sa.Column('broker_position_id', sa.String(length=100), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='position_direction_enum'), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('current_volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('floating_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('initial_risk', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'PARTIALLY_CLOSED', name='position_status_enum'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_price_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('break_even_enabled', sa.Boolean(), nullable=False),
    sa.Column('trailing_stop_enabled', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_index('ix_positions_account', 'positions', ['account_id'], unique=False)
    op.create_index('ix_positions_order', 'positions', ['order_id'], unique=False)
    op.create_index('ix_positions_status', 'positions', ['status'], unique=False)
    op.create_index('ix_positions_symbol', 'positions', ['symbol_id'], unique=False)
    op.create_index('ix_positions_ticket', 'positions', ['ticket'], unique=False)
    op.create_table('trades',
    sa.Column('ticket', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='position_direction_enum'), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('swap', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('profit_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('initial_risk', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reward_risk_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_favorable_excursion', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_adverse_excursion', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('result', sa.Enum('WIN', 'LOSS', 'BREAKEVEN', name='trade_result_enum'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id'),
    sa.UniqueConstraint('ticket')
    )
    op.create_index('ix_trade_account', 'trades', ['account_id'], unique=False)
    op.create_index('ix_trade_closed', 'trades', ['closed_at'], unique=False)
    op.create_index('ix_trade_opened', 'trades', ['opened_at'], unique=False)
    op.create_index('ix_trade_strategy', 'trades', ['strategy'], unique=False)
    op.create_index('ix_trade_symbol', 'trades', ['symbol_id'], unique=False)
    op.create_index('ix_trade_ticket', 'trades', ['ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_ticket', table_name='trades')
    op.drop_index('ix_trade_symbol', table_name='trades')
    op.drop_index('ix_trade_strategy', table_name='trades')
    op.drop_index('ix_trade_opened', table_name='trades')
    op.drop_index('ix_trade_closed', table_name='trades')
    op.drop_index('ix_trade_account', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_positions_ticket', table_name='positions')
    op.drop_index('ix_positions_symbol', table_name='positions')
    op.drop_index('ix_positions_status', table_name='positions')
    op.drop_index('ix_positions_order', table_name='positions')
    op.drop_index('ix_positions_account', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_risk_timestamp', table_name='risk_snapshots')
    op.drop_index('ix_risk_level', table_name='risk_snapshots')
    op.drop_index('ix_risk_account', table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index('ix_performance_period', table_name='performance')
    op.drop_index('ix_performance_created', table_name='performance')
    op.drop_table('performance')
    op.drop_index('ix_orders_ticket', table_name='orders')
    op.drop_index('ix_orders_symbol_id', table_name='orders')
    op.drop_index('ix_orders_strategy', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_account_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_account_symbols_symbol_id', table_name='account_symbols')
    op.drop_index('ix_account_symbols_enabled', table_name='account_symbols')
    op.drop_index('ix_account_symbols_broker_symbol', table_name='account_symbols')
    op.drop_index('ix_account_symbols_account_id', table_name='account_symbols')
    op.drop_table('account_symbols')
    op.drop_index('ix_trading_accounts_user_id', table_name='trading_accounts')
    op.drop_index('ix_trading_accounts_status', table_name='trading_accounts')
    op.drop_index('ix_trading_accounts_broker', table_name='trading_accounts')
    op.drop_table('trading_accounts')
    op.drop_index('ix_strategy_type', table_name='strategy_runs')
    op.drop_index('ix_strategy_status', table_name='strategy_runs')
    op.drop_index('ix_strategy_started', table_name='strategy_runs')
    op.drop_index('ix_strategy_name', table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_table('password_resets')
    op.drop_index('ix_historical_candles_symbol_timeframe_timestamp', table_name='historical_candles')
    op.drop_table('historical_candles')
    op.drop_index('ix_email_verification_verified', table_name='email_verifications')
    op.drop_index('ix_email_verification_user', table_name='email_verifications')
    op.drop_index('ix_email_verification_expires', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_table('users')
    op.drop_index('ix_symbols_name', table_name='symbols')
    op.drop_index('ix_symbols_asset_class', table_name='symbols')
    op.drop_index('ix_symbols_active', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_market_candles_lookup', table_name='market_candles')
    op.drop_table('market_candles')
    # ### end Alembic commands ###
