"""add strategy definition catalog

Revision ID: 3735c6f1a310
Revises: 72e0f9e75029
Create Date: 2026-09-30 08:10:17.559208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3735c6f1a310'
down_revision: Union[str, Sequence[str], None] = '72e0f9e75029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_definitions',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=500), server_default='', nullable=False),
    sa.Column('author', sa.String(length=128), server_default='', nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('module_path', sa.String(length=255), nullable=False),
    sa.Column('class_name', sa.String(length=255), nullable=False),
    sa.Column('definition_payload', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_strategy_definition_available', 'strategy_definitions', ['available'], unique=False)
    op.create_index('ix_strategy_definition_available_name', 'strategy_definitions', ['available', 'name'], unique=False)
    op.create_index('ix_strategy_definition_name', 'strategy_definitions', ['name'], unique=False)
    op.create_index('ix_strategy_definition_version', 'strategy_definitions', ['version'], unique=False)
    op.add_column('strategy_runs', sa.Column('strategy_definition_id', sa.UUID(), nullable=True))
    op.create_index('ix_strategy_account_definition', 'strategy_runs', ['account_id', 'strategy_definition_id'], unique=False)
    op.create_index('ix_strategy_definition', 'strategy_runs', ['strategy_definition_id'], unique=False)
    op.create_foreign_key(None, 'strategy_runs', 'strategy_definitions', ['strategy_definition_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_runs', type_='foreignkey')
    op.drop_index('ix_strategy_definition', table_name='strategy_runs')
    op.drop_index('ix_strategy_account_definition', table_name='strategy_runs')
    op.drop_column('strategy_runs', 'strategy_definition_id')
    op.drop_index('ix_strategy_definition_version', table_name='strategy_definitions')
    op.drop_index('ix_strategy_definition_name', table_name='strategy_definitions')
    op.drop_index('ix_strategy_definition_available_name', table_name='strategy_definitions')
    op.drop_index('ix_strategy_definition_available', table_name='strategy_definitions')
    op.drop_table('strategy_definitions')
    # ### end Alembic commands ###
