"""add historical candles

Revision ID: 4ca84f4b9a88
Revises: 214a13c83b04
Create Date: 2026-09-08 15:50:34.970492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca84f4b9a88'
down_revision: Union[str, Sequence[str], None] = '214a13c83b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_candles',
    sa.Column('symbol_id', sa.UUID(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.Column('spread', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'timestamp', name='uq_historical_candle_symbol_timeframe_timestamp')
    )
    op.create_index('ix_historical_candles_symbol_timeframe_timestamp', 'historical_candles', ['symbol_id', 'timeframe', 'timestamp'], unique=False)
    op.drop_table('risk_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_profiles',
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('base_risk_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('min_risk_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('max_risk_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('risk_multiplier', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('max_daily_loss_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('max_drawdown_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('max_open_risk_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('max_positions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_symbol_exposure_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('max_strategy_exposure_percent', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=False),
    sa.Column('hard_limits_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], name=op.f('risk_profiles_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('risk_profiles_pkey')),
    sa.UniqueConstraint('account_id', name=op.f('risk_profiles_account_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('ix_historical_candles_symbol_timeframe_timestamp', table_name='historical_candles')
    op.drop_table('historical_candles')
    # ### end Alembic commands ###
