"""update position order relationship

Revision ID: 6b139811ba4c
Revises: f16723a24436
Create Date: 2026-08-14 10:46:04.017173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b139811ba4c'
down_revision: Union[str, Sequence[str], None] = 'f16723a24436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('positions_order_id_key'), 'positions', type_='unique')
    op.create_index('ix_positions_order', 'positions', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_order', table_name='positions')
    op.create_unique_constraint(op.f('positions_order_id_key'), 'positions', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
