"""add account and enabled fields to strategy runs

Revision ID: 72e0f9e75029
Revises: e4a789dd5ab0
Create Date: 2026-09-29 16:46:27.293218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e0f9e75029'
down_revision: Union[str, Sequence[str], None] = 'e4a789dd5ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_runs', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('strategy_runs', sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False))
    op.create_index('ix_strategy_account', 'strategy_runs', ['account_id'], unique=False)
    op.create_index('ix_strategy_account_enabled', 'strategy_runs', ['account_id', 'enabled'], unique=False)
    op.create_foreign_key(None, 'strategy_runs', 'trading_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_runs', type_='foreignkey')
    op.drop_index('ix_strategy_account_enabled', table_name='strategy_runs')
    op.drop_index('ix_strategy_account', table_name='strategy_runs')
    op.drop_column('strategy_runs', 'enabled')
    op.drop_column('strategy_runs', 'account_id')
    # ### end Alembic commands ###
