"""add user model

Revision ID: 7689c26ae876
Revises: 14edfa23b98e
Create Date: 2026-08-01 17:07:08.154238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7689c26ae876'
down_revision: Union[str, Sequence[str], None] = '14edfa23b98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('strategy_runs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'strategy_runs', 'users', ['user_id'], ['id'])
    op.add_column('trading_accounts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'trading_accounts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trading_accounts', type_='foreignkey')
    op.drop_column('trading_accounts', 'user_id')
    op.drop_constraint(None, 'strategy_runs', type_='foreignkey')
    op.drop_column('strategy_runs', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
