"""make performance profit factor nullable

Revision ID: 8ad4dd9f49d6
Revises: b75c847bc891
Create Date: 2026-08-15 07:25:46.596328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad4dd9f49d6'
down_revision: Union[str, Sequence[str], None] = 'b75c847bc891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance', 'profit_factor',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance', 'profit_factor',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    # ### end Alembic commands ###
