"""add email verification

Revision ID: afe0b7f4d832
Revises: 7689c26ae876
Create Date: 2026-08-05 13:20:31.104385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "afe0b7f4d832"
down_revision: Union[str, Sequence[str], None] = "7689c26ae876"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("otp_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_email_verification_expires",
        "email_verifications",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_email_verification_user", "email_verifications", ["user_id"], unique=False
    )
    op.create_index(
        "ix_email_verification_verified",
        "email_verifications",
        ["verified"],
        unique=False,
    )


# 1. Add the column with a default
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    # 2. Remove the server default
    op.alter_column(
        "users",
        "email_verified",
        server_default=None,
    )
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_verified")
    op.drop_index("ix_email_verification_verified", table_name="email_verifications")
    op.drop_index("ix_email_verification_user", table_name="email_verifications")
    op.drop_index("ix_email_verification_expires", table_name="email_verifications")
    op.drop_table("email_verifications")
    # ### end Alembic commands ###
