"""add execution correlation to orders

Revision ID: e4a789dd5ab0
Revises: 2587a2e5e4b8
Create Date: 2026-09-24 19:09:25.732756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a789dd5ab0'
down_revision: Union[str, Sequence[str], None] = '2587a2e5e4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('execution_correlation_id', sa.Uuid(), nullable=False))
    op.create_index('ix_orders_execution_correlation_id', 'orders', ['execution_correlation_id'], unique=False)
    op.create_unique_constraint(None, 'orders', ['execution_correlation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_index('ix_orders_execution_correlation_id', table_name='orders')
    op.drop_column('orders', 'execution_correlation_id')
    # ### end Alembic commands ###
