"""add email verification

Revision ID: ecabd720a5bd
Revises: afe0b7f4d832
Create Date: 2026-08-05 13:29:35.661788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecabd720a5bd'
down_revision: Union[str, Sequence[str], None] = 'afe0b7f4d832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_verifications', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_verifications', type_='unique')
    # ### end Alembic commands ###
