"""make order requested price nullable

Revision ID: f16723a24436
Revises: faa524677e06
Create Date: 2026-08-12 15:31:59.932308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f16723a24436'
down_revision: Union[str, Sequence[str], None] = 'faa524677e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'requested_price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=True)
    op.create_index('ix_orders_account_id', 'orders', ['account_id'], unique=False)
    op.create_index('ix_orders_symbol_id', 'orders', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_symbol_id', table_name='orders')
    op.drop_index('ix_orders_account_id', table_name='orders')
    op.alter_column('orders', 'requested_price',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               nullable=False)
    # ### end Alembic commands ###
